### ISSUE TITLE
Some issue with cjs/puppeteer/common/assert.js:26

### ISSUE THREAD

**Issue by j67Sv89n** [rishabhrpg/puppeteer-on-termux#11]
If I understand it's some problem with location path in termux and proot or version nodejs?
I'm lunch code with 
"type": "module",
and
 (async () => {
  const browser = await puppeteer.launch({headless: true, args:['--no-sandbox']});

```
localhost:~/puppeteer-on-termux# node index.
js
/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: Unsupported platform: android
    at exports.assert (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/common/assert.js:26:15)
    at BrowserFetcher.setPlatform (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:175:25)
    at new BrowserFetcher (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:159:14)
    at resolveExecutablePath (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:442:28)
    at ChromeLauncher.launch (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:77:53)
    at async file:///root/puppeteer-on-termux/index.js:4:19

Node.js v19.6.1
localhost:~/puppeteer-on-termux# node --trac
e-warnings index.index.js
node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module '/root/puppeteer-on-termux/index.index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.6.1
localhost:~/puppeteer-on-termux# ls
README.md         package.json
index.js          screenshots
node_modules      yarn.lock
package.j19.4.0x
localhost:~/puppeteer-on-termux#
```

**Comment by Gamer304227** [comment]
Hello, I know I am too late but maybe someone else can be helped though this message thats why I am writing it to you.

1st error happened because **you are running it on a android phone**.

2nd error happened because you mistakenly enter "index.index.js" where you had to enter "index.js" . And because **there is no such a file named "index.index.js"** exists you got the error "Cannot find module"

**Comment by Gamer304227** [comment]
Hello, I know I am too late but maybe someone else can be helped though this message thats why I am writing it to you.

1st error happened because **you are running it on a android phone**.

2nd error happened because you mistakenly enter "index.index.js" where you had to enter "index.js" . And because **there is no such a file named "index.index.js"** exists you got the error "Cannot find module"
