### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by 41Team** [rishabhrpg/puppeteer-on-termux#9]
`localhost:~/puppeteer-on-termux#` node index.js
/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: Unsupported platform: android
    at Object.exports.assert (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/common/assert.js:26:15)
    at BrowserFetcher.setPlatform (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:175:25)
    at new BrowserFetcher (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:159:14)
    at resolveExecutablePath (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:442:28)
    at ChromeLauncher.launch (/root/puppeteer-on-termux/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:77:53)
    at async screenshot (/root/puppeteer-on-termux/index.js:7:19)

Node.js v17.7.1
localhost:~/puppeteer-on-termux#`

**Comment by alexjyong** [comment]
I'm able to get it to run, although I had to install yarn and git via `apk get yarn` and `apk get git` respectively, which I didn't see in the documentation.

Can you share the steps you did?

**Comment by rishabhrpg** [comment]
@alexjyong they are mentioned in the requirements 
Follow these setps
In the main termux shell

pkg install nodejs
pkg install git 
npm install -g yarn

Then these commands will be available in proot-distro as well.

**Comment by rishabhrpg** [comment]
@41Team this issue is fixed in a recent commit.

You need to require "puppeteer-core" and not "puppeteer"
